### ISSUE TITLE
/openidconnect/login Not Found after WAR File deployment

### ISSUE THREAD

**Issue by timnault** [GluuFederation/oxRay#2]
Using the Bitnami Liferay AMI on AWS...tried deploying the WAR got the Hook for gluu-openid-connect-hook is available for use message and no other errors on boot up yet when I browse to /openidconnect/login I get a Not Found Error. 

17:20:09,784 INFO  [localhost-startStop-1][HotDeployEvent:145] Plugin gluu-openid-connect-hook requires marketplace-portlet
17:20:09,785 INFO  [localhost-startStop-1][HotDeployImpl:217] Deploying gluu-openid-connect-hook from queue
17:20:09,785 INFO  [localhost-startStop-1][PluginPackageUtil:1016] Reading plugin package for gluu-openid-connect-hook
17:20:11,355 INFO  [localhost-startStop-1][HookHotDeployListener:709] Registering hook for gluu-openid-connect-hook
Loading file:/opt/bitnami/apache-tomcat/webapps/gluu-openid-connect-hook/WEB-INF/classes/portal.properties
17:20:11,392 INFO  [localhost-startStop-1][HookHotDeployListener:851] Hook for gluu-openid-connect-hook is available for use

/opt/bitnami/apache-tomcat/webapps/gluu-openid-connect-hook/WEB-INF/classes/portal.properties with the gluu configs as per the directions...
gluu.openidconnect.auth.enabled=true
gluu.openidconnect.client.id=@!bla.bla.bla
gluu.openidconnect.client.secret=bla-bla-bla-bla-bla
gluu.openidconnect.idp.domain=https://idp.bla.com
gluu.openidconnect.url.discovery=https://idp.bla.com/.well-known/openid-configuration
gluu.openidconnect.client.redirect.url=https://rp.bla.com/openidconnect/callback
gluu.openidconnect.no.such.user.redirect.url=https://rp.bla.com/no-such-user-found

Any thoughts on why the hook is not registering?

**Comment by willow9886** [comment]
hey @timnault we haven't maintained oxRay due to lack of demand. 

However, we do have a newly developed Magento extension for our oxD mediator. Take a look [here](https://gluu.org/docs-oxd/plugin/php/cms/magento/). 

It requires that you have a Gluu Server setup and oxD sitting on the same web server as your Magento site. Perhaps this can satisfy your requirement instead. Let us know how it goes... 

If you run into any trouble, best place to get troubleshooting assistance is our [support portal](http://support.guluu.org).

Thanks!

**Comment by willow9886** [comment]
I also just added a note to the project readme explaining so much. Sorry for the inconvenience!
